// Generated by Wrangler on Sat Mar 09 2024 17:31:15 GMT+0100 (GMT+01:00)
// by running `wrangler types`

interface Env {
  SANITY_STUDIO_PROJECT_ID: "890pwjuq";
  SANITY_STUDIO_DATASET: "production";
}
